import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    name: 'Crispy Calamari',
    description: 'Golden-fried calamari rings served with a zesty marinara sauce.',
    price: 14.99,
    image: 'https://picsum.photos/id/1060/600/400',
    category: 'Appetizers',
    nutrition: { calories: 450, protein: 25, carbs: 35, fat: 22 },
  },
  {
    id: 2,
    name: 'Bruschetta al Pomodoro',
    description: 'Toasted ciabatta bread topped with fresh tomatoes, garlic, basil, and olive oil.',
    price: 11.50,
    image: 'https://picsum.photos/id/25/600/400',
    category: 'Appetizers',
    nutrition: { calories: 250, protein: 6, carbs: 30, fat: 12 },
  },
  {
    id: 3,
    name: 'Wagyu Burger',
    description: 'Juicy Wagyu beef patty with cheddar, lettuce, tomato, and our secret sauce.',
    price: 24.00,
    image: 'https://picsum.photos/id/102/600/400',
    category: 'Main Courses',
    nutrition: { calories: 850, protein: 45, carbs: 40, fat: 55 },
  },
  {
    id: 4,
    name: 'Grilled Salmon',
    description: 'Perfectly grilled salmon fillet with a lemon-dill sauce, served with asparagus.',
    price: 28.50,
    image: 'https://picsum.photos/id/366/600/400',
    category: 'Main Courses',
    nutrition: { calories: 600, protein: 50, carbs: 15, fat: 38 },
  },
  {
    id: 5,
    name: 'Spaghetti Carbonara',
    description: 'Classic pasta with pancetta, pecorino cheese, and a creamy egg sauce.',
    price: 21.00,
    image: 'https://picsum.photos/id/431/600/400',
    category: 'Main Courses',
    nutrition: { calories: 750, protein: 30, carbs: 80, fat: 35 },
  },
  {
    id: 6,
    name: 'Tiramisu',
    description: 'Layers of coffee-soaked ladyfingers and mascarpone cream, dusted with cocoa.',
    price: 10.50,
    image: 'https://picsum.photos/id/225/600/400',
    category: 'Desserts',
    nutrition: { calories: 550, protein: 8, carbs: 60, fat: 30 },
  },
  {
    id: 7,
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a gooey molten center, served with vanilla ice cream.',
    price: 11.00,
    image: 'https://picsum.photos/id/429/600/400',
    category: 'Desserts',
    nutrition: { calories: 620, protein: 7, carbs: 75, fat: 32 },
  },
  {
    id: 8,
    name: 'Artisanal Lemonade',
    description: 'Freshly squeezed lemonade with a hint of mint.',
    price: 6.50,
    image: 'https://picsum.photos/id/1015/600/400',
    category: 'Beverages',
    nutrition: { calories: 150, protein: 0, carbs: 40, fat: 0 },
  },
   {
    id: 9,
    name: 'Espresso Martini',
    description: 'A rich and smooth cocktail of vodka, coffee liqueur, and fresh espresso.',
    price: 15.00,
    image: 'https://picsum.photos/id/355/600/400',
    category: 'Beverages',
    nutrition: { calories: 280, protein: 1, carbs: 25, fat: 0 },
  },
];